language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build
